### ISSUE TITLE
Locking Ticket does not work

### ISSUE THREAD

**Issue by BeyondBoy1** [Arisamiga/Discord-Ticket-Bot#1]
The ticket cannot be locked

**Comment by Arisamiga** [comment]
Hello @BeyondBoy1!
Thanks for bringing this to my attention. 

Please note the following:
+  When you lock a channel it will not bring up a message and it will only lock the channel.
+ Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel

Does the console display a error of any kind?

**Comment by BeyondBoy1** [comment]
> Hello @BeyondBoy1!
> Thanks for bringing this to my attention.
> 
> Please note the following:
> 
> * When you lock a channel it will not bring up a message and it will only lock the channel.
> * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> 
> Does the console display a error of any kind?

No console log error

**Comment by Arisamiga** [comment]
> > Hello @BeyondBoy1!
> > Thanks for bringing this to my attention.
> > 
> > Please note the following:
> > 
> > * When you lock a channel it will not bring up a message and it will only lock the channel.
> > * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> > 
> > Does the console display a error of any kind?
> 
> No console log error

Does the bot change the Send message permissions on the channel for the person who created the ticket?

**Comment by BeyondBoy1** [comment]
> > > Hello @BeyondBoy1!
> > > Thanks for bringing this to my attention.
> > > Please note the following:
> > > 
> > > * When you lock a channel it will not bring up a message and it will only lock the channel.
> > > * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> > > 
> > > Does the console display a error of any kind?
> > 
> > 
> > No console log error
> 
> Does the bot change the Send message permissions on the channel for the person who created the ticket?

No it does not.

**Comment by Arisamiga** [comment]
> > > > Hello @BeyondBoy1!
> > > > Thanks for bringing this to my attention.
> > > > Please note the following:
> > > > 
> > > > * When you lock a channel it will not bring up a message and it will only lock the channel.
> > > > * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> > > > 
> > > > Does the console display a error of any kind?
> > > 
> > > 
> > > No console log error
> > 
> > Does the bot change the Send message permissions on the channel for the person who created the ticket?
> 
> No it does not.

Please make sure the bot has the premissions to change channel settings.

**Comment by BeyondBoy1** [comment]
> > > > > Hello @BeyondBoy1!
> > > > > Thanks for bringing this to my attention.
> > > > > Please note the following:
> > > > > 
> > > > > * When you lock a channel it will not bring up a message and it will only lock the channel.
> > > > > * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> > > > > 
> > > > > Does the console display a error of any kind?
> > > > 
> > > > 
> > > > No console log error
> > > 
> > > 
> > > Does the bot change the Send message permissions on the channel for the person who created the ticket?
> > 
> > 
> > No it does not.
> 
> Please make sure the bot has the premissions to change channel settings.

The bot role has permissions to change channel settings

**Comment by Arisamiga** [comment]
> > > > > > Hello @BeyondBoy1!
> > > > > > Thanks for bringing this to my attention.
> > > > > > Please note the following:
> > > > > > 
> > > > > > * When you lock a channel it will not bring up a message and it will only lock the channel.
> > > > > > * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> > > > > > 
> > > > > > Does the console display a error of any kind?
> > > > > 
> > > > > 
> > > > > No console log error
> > > > 
> > > > 
> > > > Does the bot change the Send message permissions on the channel for the person who created the ticket?
> > > 
> > > 
> > > No it does not.
> > 
> > Please make sure the bot has the premissions to change channel settings.
> 
> The bot role has permissions to change channel settings

Please note that if a channel was already made after a restart of the bot then the bot will not be able to control that channel anymore.

**Comment by BeyondBoy1** [comment]
> > > > > > > Hello @BeyondBoy1!
> > > > > > > Thanks for bringing this to my attention.
> > > > > > > Please note the following:
> > > > > > > 
> > > > > > > * When you lock a channel it will not bring up a message and it will only lock the channel.
> > > > > > > * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> > > > > > > 
> > > > > > > Does the console display a error of any kind?
> > > > > > 
> > > > > > 
> > > > > > No console log error
> > > > > 
> > > > > 
> > > > > Does the bot change the Send message permissions on the channel for the person who created the ticket?
> > > > 
> > > > 
> > > > No it does not.
> > > 
> > > 
> > > Please make sure the bot has the premissions to change channel settings.
> > 
> > 
> > The bot role has permissions to change channel settings
> 
> Please note that if a channel was already made after a restart of the bot then the bot will not be able to control that channel anymore.

The bot had no problems creating the channel after the restart, any console.log message we can add to show that channel was locked.

**Comment by Arisamiga** [comment]
> > > > > > > > Hello @BeyondBoy1!
> > > > > > > > Thanks for bringing this to my attention.
> > > > > > > > Please note the following:
> > > > > > > > 
> > > > > > > > * When you lock a channel it will not bring up a message and it will only lock the channel.
> > > > > > > > * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> > > > > > > > 
> > > > > > > > Does the console display a error of any kind?
> > > > > > > 
> > > > > > > 
> > > > > > > No console log error
> > > > > > 
> > > > > > 
> > > > > > Does the bot change the Send message permissions on the channel for the person who created the ticket?
> > > > > 
> > > > > 
> > > > > No it does not.
> > > > 
> > > > 
> > > > Please make sure the bot has the premissions to change channel settings.
> > > 
> > > 
> > > The bot role has permissions to change channel settings
> > 
> > Please note that if a channel was already made after a restart of the bot then the bot will not be able to control that channel anymore.
> 
> The bot had no problems creating the channel after the restart, any console.log message we can add to show that channel was locked.

Yes i will add it right away!

**Comment by BeyondBoy1** [comment]
> > > > > > > > > Hello @BeyondBoy1!
> > > > > > > > > Thanks for bringing this to my attention.
> > > > > > > > > Please note the following:
> > > > > > > > > 
> > > > > > > > > * When you lock a channel it will not bring up a message and it will only lock the channel.
> > > > > > > > > * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> > > > > > > > > 
> > > > > > > > > Does the console display a error of any kind?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > No console log error
> > > > > > > 
> > > > > > > 
> > > > > > > Does the bot change the Send message permissions on the channel for the person who created the ticket?
> > > > > > 
> > > > > > 
> > > > > > No it does not.
> > > > > 
> > > > > 
> > > > > Please make sure the bot has the premissions to change channel settings.
> > > > 
> > > > 
> > > > The bot role has permissions to change channel settings
> > > 
> > > 
> > > Please note that if a channel was already made after a restart of the bot then the bot will not be able to control that channel anymore.
> > 
> > 
> > The bot had no problems creating the channel after the restart, any console.log message we can add to show that channel was locked.
> 
> Yes i will add it right away!

Thanks! btw, is there a transcript and unlock channel feature?

**Comment by Arisamiga** [comment]
> > > > > > > > > > Hello @BeyondBoy1!
> > > > > > > > > > Thanks for bringing this to my attention.
> > > > > > > > > > Please note the following:
> > > > > > > > > > 
> > > > > > > > > > * When you lock a channel it will not bring up a message and it will only lock the channel.
> > > > > > > > > > * Make sure the role of the bot is higher than the role of the person who created the channel or else the bot cannot prevent the person from sending a message in the channel
> > > > > > > > > > 
> > > > > > > > > > Does the console display a error of any kind?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > No console log error
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Does the bot change the Send message permissions on the channel for the person who created the ticket?
> > > > > > > 
> > > > > > > 
> > > > > > > No it does not.
> > > > > > 
> > > > > > 
> > > > > > Please make sure the bot has the premissions to change channel settings.
> > > > > 
> > > > > 
> > > > > The bot role has permissions to change channel settings
> > > > 
> > > > 
> > > > Please note that if a channel was already made after a restart of the bot then the bot will not be able to control that channel anymore.
> > > 
> > > 
> > > The bot had no problems creating the channel after the restart, any console.log message we can add to show that channel was locked.
> > 
> > Yes i will add it right away!
> 
> Thanks! btw, is there a transcript and unlock channel feature?

Not yet but these features might be added in the future!

**Comment by Arisamiga** [comment]
Added Message when channel is locked 3683fa9dbe14c36be052e7cbf810da97287dee35
#

Please redownload the zip file and replace the old startapps.js with the new one.

**Comment by BeyondBoy1** [comment]
> Added Message when channel is locked [3683fa9](https://github.com/Arisamiga/Discord-Ticket-Bot/commit/3683fa9dbe14c36be052e7cbf810da97287dee35)
> 
> Please redownload the zip file and replace the old startapps.js with the new one.

Sorry, the message is sent, but the channel is not being locked.

**Comment by Arisamiga** [comment]
> > Added Message when channel is locked [3683fa9](https://github.com/Arisamiga/Discord-Ticket-Bot/commit/3683fa9dbe14c36be052e7cbf810da97287dee35)
> > 
> > Please redownload the zip file and replace the old startapps.js with the new one.
> 
> Sorry, the message is sent, but the channel is not being locked.

Uhh that's strange.. I tested it and it works for me. Please note the following as it may be the source of the problem:

+ The channel the bot has created should not be edited by adding additional roles etc.

+ If the person who created the channel is a Administrator then the lock wouldn't affect the person as he/she can bypass the channel restrictions

+ The bot cannot control a channel that was made before the restart of the bot

+ The bot has to have the Premissions to manage channels in order to lock them.

If those dont work then i suggest you reinstall the code and try again.

**Comment by BeyondBoy1** [comment]
> > > Added Message when channel is locked [3683fa9](https://github.com/Arisamiga/Discord-Ticket-Bot/commit/3683fa9dbe14c36be052e7cbf810da97287dee35)
> > > Please redownload the zip file and replace the old startapps.js with the new one.
> > 
> > 
> > Sorry, the message is sent, but the channel is not being locked.
> 
> Uhh that's strange.. I tested it and it works for me. Please note the following as it may be the source of the problem:
> 
> * The channel the bot has created should not be edited by adding additional roles etc.
> * If the person who created the channel is a Administrator then the lock wouldn't affect the person as he/she can bypass the channel restrictions
> * The bot cannot control a channel that was made before the restart of the bot
> * The bot has to have the Premissions to manage channels in order to lock them.
> 
> If those dont work then i suggest you reinstall the code and try again.

It's fine, I found another solution for it, thanks anyway and good luck with your bot.
