### ISSUE TITLE
Ideas to improve locking system

### ISSUE THREAD

**Issue by Nikki-Devil** [Arisamiga/Discord-Ticket-Bot#10]
I have two suggestions to improve the locking system

First is to prevent spamming the lock
At the moment, each time you add the reaction to lock, it sends a message, so when you remove your reaction and add it back it sends the message to inform that the ticket is locked

Second is to let those with channel role the unlocking the channel
I don't have use case example for this one but it may be useful

**Comment by Arisamiga** [comment]
Thanks so much for the suggestion :D

I have added the changes here https://github.com/Arisamiga/Discord-Ticket-Bot/commit/ed03793e53b2455e59dbc434c100f1ec7e5b4941 

Also now you have a toggle in the config if you want the user to be able to unlock or not but also not if a staff member locks the ticket it will lock the owner of the ticket and **not** the staff member.

If you experience any issues let me know by opening a issue.
