### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by JasperzDev** [Arisamiga/Discord-Ticket-Bot#2]
Would be better if you can add a staff role to the tickets?

**Comment by Arisamiga** [comment]
> Would be better if you can add a staff role to the tickets?

I will create a different branch for that so you can use that instead!

**Comment by Arisamiga** [comment]
> > Would be better if you can add a staff role to the tickets?
> 
> I will create a different branch for that so you can use that instead!


You can find the new feature [here](https://github.com/Arisamiga/Discord-Ticket-Bot/tree/RoleViewer)!
