### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by Psykopaten** [Arisamiga/Discord-Ticket-Bot#4]
I can realy see whats the problem but it looks like **code: 'MODULE_NOT_FOUND',**

![image](https://user-images.githubusercontent.com/104300989/180796253-8023fd1c-fc4f-4bf8-a28a-2c58709a660d.png)

**Comment by Arisamiga** [comment]
> I can realy see whats the problem but it looks like **code: 'MODULE_NOT_FOUND',**
> 
> ![image](https://user-images.githubusercontent.com/104300989/180796253-8023fd1c-fc4f-4bf8-a28a-2c58709a660d.png)
> 

Hello! 

It looks like the modules that are used by the bot are not installed try to use `npm install` and then try to run it again.

**Comment by Psykopaten** [comment]
oh.. yeah, thank you!
