### ISSUE TITLE
Add message ID saving

### ISSUE THREAD

**Issue by Nikki-Devil** [Arisamiga/Discord-Ticket-Bot#7]
It would be a good idea to create a file that keep track of the message IDs sent by the bot (to remember which message to check after a bot/system restart instead of having to initiate it everytime - also to remember the opened tickets)
And if it's added, support the deletion of bad IDs (like deleting the IDs of messages that no longer exist)

**Comment by Arisamiga** [comment]
Thanks so much for the feature Idea this is quite an interesting one.

Now the bot will have the collectors.json where it will save the tickets and other embeds so it will be ok to reboot the bot.

It was added with the latest commit https://github.com/Arisamiga/Discord-Ticket-Bot/commit/ea8977eb156ac440d93847c0a769e3f77340ac0c

If you experience any issues let me know by opening a issue.
