### ISSUE TITLE
Add support for multiple Channelrole

### ISSUE THREAD

**Issue by Nikki-Devil** [Arisamiga/Discord-Ticket-Bot#8]
As the title says
An exemple of use case could be if a server has Admins (without administrator permissions) and Moderators, then only one of the two could help, it would be even more useful in case the server also has a Helper role

I think allowing something like IDROLE1;IDROLE2 or IDROLE1,IDROLE2 would be a good way to setting it in the config
I'm not sure of how to do it inside the code however

**Comment by Arisamiga** [comment]
Thanks so much for the feature Idea!

This was added with the latest commit https://github.com/Arisamiga/Discord-Ticket-Bot/commit/ea8977eb156ac440d93847c0a769e3f77340ac0c

If you experience any issues let me know by opening a issue.
